-- Create a function to trigger order creation notification
CREATE OR REPLACE FUNCTION trigger_order_creation_notification()
RETURNS TRIGGER AS $$
BEGIN
  -- Only trigger for customer orders (not waiter orders) with pending_payment status
  IF NEW.status = 'pending_payment' AND NEW.waiter_id IS NULL THEN
    -- Insert notification into queue
    INSERT INTO whatsapp_notifications (
      order_id,
      customer_phone,
      notification_type,
      message_content,
      status,
      attempts,
      scheduled_at
    )
    VALUES (
      NEW.id,
      NEW.customer_phone,
      'order_created',
      '', -- Message will be generated by the queue processor
      'pending',
      0,
      NOW()
    );
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create trigger on orders table
DROP TRIGGER IF EXISTS on_order_created_notification ON orders;
CREATE TRIGGER on_order_created_notification
  AFTER INSERT ON orders
  FOR EACH ROW
  EXECUTE FUNCTION trigger_order_creation_notification();

-- Grant necessary permissions
GRANT EXECUTE ON FUNCTION trigger_order_creation_notification() TO authenticated;
GRANT EXECUTE ON FUNCTION trigger_order_creation_notification() TO anon;
